import { Layout } from "@/components/Layout";
import Head from "next/head";
import Image from "next/image";
import AI_Image from "../../public/AI_Image.png";
import { AnimatedText } from "@/components/AnimatedText";
import Link from "next/link";
import { ExternalLinkIcon } from "@/components/Icons";
export default function Home() {
  return (
    <>
      <Head>
        <title>Vladimir's Portofolio</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="flex items-center text-dark w-full min-h-screen">
        <Layout className="pt-0">
          <div className="flex items-center justify-between w-full">
            <div className="w-1/2">
              <Image
                src={AI_Image}
                alt="Vladimir"
                className="w-full h-auto"
              ></Image>
            </div>
            <div className="w-1/2 flex flex-col items-center self-center">
              <AnimatedText
                text="Turning vision into reality with code and design"
                className="!text-6xl !text-left xl:!text-5xl lg:!text-center lg:!text-6xl md:!text-5xl sm:!text-3xl"
              />
              <p className="my-4 !text-xl font-medium">
                As a skilled full-stack developer, I am dedicated to turning
                ideas into innovative web applications. Explore my latest
                projects and articles, showcasing my expertise
              </p>
              <div className="flex items-center self-start mt-2">
                <Link
                  href="/dummy.pdf"
                  target={"_blank"}
                  className="flex items-center bg-dark text-light p-2.5 px-6 rounded-lg text-lg font-semibold hover:bg-light hover:text-dark
                  border-2 border-solid border-transparent hover:border-dark"
                  download={true}
                >
                  Resume
                  {/* <ExternalLinkIcon className={"w-6 ml-1"}/> */}
                </Link>
                <Link
                  href="mailto:vladimir.nitu.business@outlook.com"
                  target={"_blank"}
                  className="ml-4 text-lg font-medium capitalize text-dark underline"
                >
                  Contact
                </Link>
              </div>
            </div>
          </div>
        </Layout>
      </main>
    </>
  );
}
